namespace Hoshi.Core.Localization;

public static partial class Tr
{
    static partial void AddViews(Dictionary<string, (string En, string Es)> d)
    {
        Add(d, "Prefs.Language", "Language", "Idioma");
        Add(d, "Main.Replays", "Played games…", "Partidas jugadas…");
        Add(d, "KataGo.Title", "KataGo is not installed", "KataGo no está instalado");
        Add(d, "KataGo.Explanation", "The AI analysis, the move effects and the adaptive music need KataGo. Hoshi can download the official build and a small, quick network for you.", "El análisis con IA, los efectos de las jugadas y la música adaptativa necesitan KataGo. Hoshi puede descargar la versión oficial y una red pequeña y rápida por ti.");
        Add(d, "KataGo.Install", "Install KataGo (≈{0} MB)", "Instalar KataGo (≈{0} MB)");
        Add(d, "KataGo.NotNow", "Not now", "Ahora no");
        Add(d, "KataGo.PrefsHint", "Leave the paths empty to use the KataGo that comes with Hoshi (or install it here).", "Deja las rutas vacías para usar el KataGo que trae Hoshi (o instálalo aquí).");
        Add(d, "Online.Chat", "Chat", "Chat");
        Add(d, "Online.ChatMute", "Mute", "Silenciar");
        Add(d, "Online.ChatMuteTip", "Hide and silence your opponent's messages for this game (handy to concentrate).", "Oculta y silencia los mensajes del rival en esta partida (útil para concentrarte).");
        Add(d, "Online.ChatEmpty", "No messages yet. Say hi with a quick phrase: your opponent reads it in their language.", "Aún no hay mensajes. Saluda con una frase rápida: tu rival la lee en su idioma.");
        Add(d, "Prefs.ChatSoundsBox", "Soft sound for new chat messages in online games", "Sonido suave con los mensajes nuevos del chat en partidas en línea");
        Add(d, "Main.CheckUpdates", "Check for updates…", "Buscar actualizaciones…");
        Add(d, "Prefs.CheckForUpdates", "Check for updates automatically", "Buscar actualizaciones automáticamente");
        Add(d, "Prefs.UpdatesHint", "This is Hoshi {0}. Hoshi asks GitHub for the latest release shortly after it starts and every 12 hours; nothing about you is sent.", "Esta es Hoshi {0}. Hoshi pregunta a GitHub por la última versión poco después de abrirse y cada 12 horas; no se envía nada sobre ti.");
        Add(d, "Update.Available", "Hoshi {0} is available (you have {1}).", "Hoshi {0} está disponible (tienes la {1}).");
        Add(d, "Update.Install", "Update and restart", "Actualizar y reiniciar");
        Add(d, "Update.Download", "Get the installer", "Descargar el instalador");
        Add(d, "Update.InstallerHint", "Install Hoshi with its installer once and it will keep itself up to date.", "Instala Hoshi con su instalador una vez y se mantendrá al día solo.");
        Add(d, "Update.Later", "Later", "Más tarde");
        Add(d, "Update.Skip", "Skip this version", "Saltar esta versión");
        Add(d, "Update.Checking", "Checking for updates…", "Buscando actualizaciones…");
        Add(d, "Update.UpToDate", "You have the latest version ({0}).", "Tienes la última versión ({0}).");
        Add(d, "Update.CheckFailed", "Could not reach GitHub to check for updates.", "No se pudo consultar GitHub para buscar actualizaciones.");
        Add(d, "Update.Downloading", "Downloading… {0} %", "Descargando… {0} %");
        Add(d, "Update.Installing", "Installing…", "Instalando…");
        Add(d, "Update.Restarting", "Restarting Hoshi…", "Reiniciando Hoshi…");
        Add(d, "Update.Failed", "The update failed: {0}", "La actualización falló: {0}");
        Add(d, "Update.AfterGame", "Finish your OGS game first; the update will wait.", "Termina primero tu partida de OGS; la actualización esperará.");
        Add(d, "Main.Joseki", "Joseki trainer", "Entrenador de josekis");

        // Joseki trainer
        Add(d, "Joseki.Title", "Joseki trainer", "Entrenador de josekis");
        Add(d, "Joseki.Next", "Next line", "Siguiente línea");
        Add(d, "Joseki.Restart", "Again", "Otra vez");
        Add(d, "Joseki.ShowAnswer", "Show answer", "Ver respuesta");
        Add(d, "Joseki.Import", "Import SGF…", "Importar SGF…");
        Add(d, "Joseki.AddFromBoard", "Add line from the main board", "Añadir la línea del tablero principal");
        Add(d, "Joseki.AddFromBoardTip", "Saves the moves from the start to the current position of the main board as a joseki line.", "Guarda las jugadas desde el inicio hasta la posición actual del tablero principal como línea de joseki.");
        Add(d, "Joseki.Help", "Place every stone of the joseki, both colours. A mirror image is fine. Pick a line from the list or let the trainer choose what is due: perfect lines come back later and later, missed ones soon. N next · H answer · R again · Esc back to the game.", "Coloca cada piedra del joseki, de los dos colores. Vale también su imagen en espejo. Elige una línea de la lista o deja que el entrenador elija lo pendiente: las perfectas vuelven cada vez más tarde, las falladas pronto. N siguiente · H respuesta · R otra vez · Esc volver a la partida.");
        Add(d, "Joseki.Progress", "Move {0} of {1} · {2} to play", "Jugada {0} de {1} · juegan {2}");
        Add(d, "Joseki.Box", "Box {0} of {1}", "Caja {0} de {1}");
        Add(d, "Joseki.NewLine", "New line", "Línea nueva");
        Add(d, "Joseki.LibraryStats", "{0} lines · {1} due · {2} learned", "{0} líneas · {1} pendientes · {2} aprendidas");
        Add(d, "Joseki.Start", "Your move: play the first stone of the joseki.", "Te toca: juega la primera piedra del joseki.");
        Add(d, "Joseki.ExtraPractice", "Nothing due right now: extra practice.", "Nada pendiente por ahora: práctica extra.");
        Add(d, "Joseki.Correct", "Right. Next stone.", "Bien. Siguiente piedra.");
        Add(d, "Joseki.Mirror", "Right (the mirror image). Next stone.", "Bien (su imagen en espejo). Siguiente piedra.");
        Add(d, "Joseki.AlsoJoseki", "That is joseki too, but this line goes another way. Try again.", "Eso también es joseki, pero esta línea sigue de otra forma. Prueba otra vez.");
        Add(d, "Joseki.Wrong", "Not this one. Try again.", "Esa no. Prueba otra vez.");
        Add(d, "Joseki.Revealed", "The circle shows the move.", "El círculo marca la jugada.");
        Add(d, "Joseki.Done", "Perfect! This line comes back later.", "¡Perfecto! Esta línea volverá más adelante.");
        Add(d, "Joseki.DoneWithMistakes", "Done, with mistakes: this line comes back soon.", "Terminada, con errores: esta línea volverá pronto.");
        Add(d, "Joseki.NoLines", "No joseki lines yet. Import an SGF collection or add a line from the main board.", "Aún no hay líneas de joseki. Importa una colección SGF o añade una línea del tablero principal.");
        Add(d, "Joseki.Imported", "Imported: {0} new lines.", "Importado: {0} líneas nuevas.");
        Add(d, "Joseki.ImportFailed", "Could not import the file", "No se pudo importar el archivo");
        Add(d, "Joseki.NoLinesInFile", "The file has no joseki lines (sequences of at least two moves from an empty board, up to 19×19).", "El archivo no tiene líneas de joseki (secuencias de al menos dos jugadas desde el tablero vacío, hasta 19×19).");
        Add(d, "Joseki.Added", "Line added to your library.", "Línea añadida a tu biblioteca.");
        Add(d, "Joseki.AddTooShort", "Play at least two moves on the main board first.", "Primero juega al menos dos jugadas en el tablero principal.");
        Add(d, "Joseki.AddKnown", "That line is already in your library.", "Esa línea ya está en tu biblioteca.");
        Add(d, "Joseki.MyLineName", "My line {0}", "Mi línea {0}");
        Add(d, "Joseki.BlockedOnline", "The trainer is closed while you are playing a game on OGS, to keep your games fair.", "El entrenador está cerrado mientras juegas una partida en OGS, para que tus partidas sean limpias.");
        Add(d, "Main.JosekiHints", "Joseki", "Joseki");
        Add(d, "Main.JosekiTip", "Show known joseki continuations in each corner (J): green ideal, olive good, yellow trick, blue open question, red mistake, violet from your library. Off during your OGS games.", "Muestra las continuaciones de joseki conocidas en cada esquina (J): verde ideal, oliva buena, amarillo truco, azul dudosa, rojo error, violeta de tu biblioteca. Apagado durante tus partidas en OGS.");
        Add(d, "Joseki.BackToGame", "Back to the game (Esc)", "Volver a la partida (Esc)");
        Add(d, "Joseki.Fetch", "New line from OGS", "Nueva línea de OGS");
        Add(d, "Joseki.FetchTip", "Builds a new line from the OGS Joseki Explorer (ideal and good moves only) in the chosen family, and keeps it in your library.", "Crea una línea nueva con el Joseki Explorer de OGS (solo jugadas ideales y buenas) de la familia elegida, y la guarda en tu biblioteca.");
        Add(d, "Joseki.Fetching", "Asking the OGS Joseki Explorer…", "Consultando el Joseki Explorer de OGS…");
        Add(d, "Joseki.Fetched", "New line from the OGS Joseki Explorer. Your move.", "Línea nueva del Joseki Explorer de OGS. Te toca.");
        Add(d, "Joseki.FetchFailed", "Could not reach the OGS Joseki Explorer. Check your connection and try again.", "No se pudo consultar el Joseki Explorer de OGS. Revisa la conexión y prueba otra vez.");
        Add(d, "Joseki.FetchNothingNew", "The explorer only gave lines you already have; try again or pick another family.", "El explorador solo dio líneas que ya tienes; prueba otra vez o elige otra familia.");
        Add(d, "Joseki.OgsLineName", "OGS · {0} · {1} moves", "OGS · {0} · {1} jugadas");
        Add(d, "Joseki.NoLinesInFamily", "No lines of this family yet. Fetch one from OGS or pick another family.", "Aún no hay líneas de esta familia. Trae una de OGS o elige otra familia.");
        Add(d, "Joseki.Family.All", "All families", "Todas las familias");
        Add(d, "Joseki.Family.Hoshi", "4-4 (hoshi)", "4-4 (hoshi)");
        Add(d, "Joseki.Family.Komoku", "3-4 (komoku)", "3-4 (komoku)");
        Add(d, "Joseki.Family.SanSan", "3-3 (san-san)", "3-3 (san-san)");
        Add(d, "Joseki.Family.Takamoku", "4-5 (takamoku)", "4-5 (takamoku)");
        Add(d, "Joseki.Family.Mokuhazushi", "3-5 (mokuhazushi)", "3-5 (mokuhazushi)");
        Add(d, "Joseki.Family.Other", "Other", "Otras");
        Add(d, "Joseki.Hint.Ogs", "Joseki (OGS): {0} · {1} continuations", "Joseki (OGS): {0} · {1} continuaciones");
        Add(d, "Joseki.Hint.Library", "Joseki (your library) · {0} continuations", "Joseki (tu biblioteca) · {0} continuaciones");
        Add(d, "Joseki.Hint.Unknown", "This corner has left the known joseki", "Esta esquina ya salió del joseki conocido");
        Add(d, "Joseki.Hint.Offline", "OGS Joseki Explorer unreachable · {0} from your library", "Joseki Explorer de OGS no disponible · {0} de tu biblioteca");
        Add(d, "Joseki.Legend.Title", "Joseki", "Joseki");
        Add(d, "Joseki.Legend.Ideal", "Ideal", "Ideal");
        Add(d, "Joseki.Legend.Good", "Good", "Buena");
        Add(d, "Joseki.Legend.Trick", "Trick play", "Truco");
        Add(d, "Joseki.Legend.Question", "Open question", "Dudosa");
        Add(d, "Joseki.Legend.Mistake", "Mistake", "Error");
        Add(d, "Joseki.Legend.Library", "Your library", "Tu biblioteca");
        Add(d, "Joseki.Legend.Tip", "Ratings come from the OGS Joseki Explorer; violet discs are lines from your own library. Small discs (mistakes, tricks, open questions) are shown, not recommended.", "Las valoraciones vienen del Joseki Explorer de OGS; los discos violeta son líneas de tu propia biblioteca. Los discos pequeños (errores, trucos, dudosas) se muestran, pero no se recomiendan.");
        Add(d, "Joseki.Note.Completed", "Completes “{0}”: {1}", "Completa «{0}»: {1}");
        Add(d, "Joseki.Note.CompletedNoComment", "Completes “{0}”.", "Completa «{0}».");
        Add(d, "Joseki.Note.Following", "Follows: {0}", "Sigue: {0}");
        Add(d, "Joseki.Category.Ideal", "ideal", "ideal");
        Add(d, "Joseki.Category.Good", "good", "buena");
        Add(d, "Joseki.Category.Mistake", "mistake", "error");
        Add(d, "Joseki.Category.Trick", "trick play", "truco");
        Add(d, "Joseki.Category.Question", "open question", "dudosa");
        Add(d, "Joseki.Category.Unknown", "unrated", "sin valorar");
        Add(d, "Joseki.Starter.Invasion33", "3-3 invasion under the 4-4 point", "Invasión en 3-3 bajo el hoshi");
        Add(d, "Joseki.Starter.Invasion33.Note", "White lives in the corner; Black gets outside thickness and sente.", "Blancas viven en la esquina; Negras obtienen grosor exterior y sente.");
        Add(d, "Replays.Title", "Played games", "Partidas jugadas");
        Add(d, "Replays.Hint", "Every game you play in Hoshi is kept here. Open one to review it: step forward with → and KataGo judges each move, with its effects and music.", "Aquí se guarda cada partida que juegas en Hoshi. Abre una para revisarla: avanza con → y KataGo valora cada jugada, con sus efectos y su música.");
        Add(d, "Replays.Review", "Review", "Revisar");
        Add(d, "Replays.Delete", "Delete", "Borrar");
        Add(d, "Replays.Empty", "No games yet. Games of 10 moves or more are kept automatically.", "Aún no hay partidas. Se guardan solas las de 10 jugadas o más.");
        Add(d, "Replays.Moves", "{0} moves", "{0} jugadas");
        Add(d, "Replays.NoResult", "no result", "sin resultado");
        Add(d, "Replays.Local", "local", "local");
        Add(d, "Replays.CouldNotOpen", "Could not open the game", "No se pudo abrir la partida");
        Add(d, "Prefs.Animations", "Animations", "Animaciones");
        Add(d, "Prefs.SoundsHelp",
            "Good: a dry knock · Excellent: an explosion with a shockwave and a shake · Best: a cinematic explosion, glowing cracks and a strong shake. The sounds are Hoshi's own; to use yours, put impact_small, explosion_medium, explosion_big or stone (.wav or .mp3) in {0}. The board impact needs animations on (Appearance).",
            "Buena: golpe seco · Excelente: explosión con onda expansiva y temblor · La mejor: explosión cinemática, grietas incandescentes y temblor fuerte. Los sonidos son de Hoshi; para usar los tuyos, pon impact_small, explosion_medium, explosion_big o stone (.wav o .mp3) en {0}. El impacto visual necesita las animaciones activadas (Apariencia).");
        Add(d, "Common.Cancel", "Cancel", "Cancelar");
        Add(d, "Common.Ok", "OK", "Aceptar");
        Add(d, "GameInfo.Date", "Date", "Fecha");
        Add(d, "GameInfo.DateFormat", "YYYY-MM-DD", "AAAA-MM-DD");
        Add(d, "GameInfo.Event", "Event", "Evento");
        Add(d, "GameInfo.Name", "Name", "Nombre");
        Add(d, "GameInfo.Place", "Place", "Lugar");
        Add(d, "GameInfo.Rank", "Rank", "Rango");
        Add(d, "GameInfo.Result", "Result", "Resultado");
        Add(d, "GameInfo.Rules", "Rules", "Reglas");
        Add(d, "GameInfo.Title", "Game info", "Información de la partida");
        Add(d, "Lobby.AutomatchSoon", "Automatic matchmaking is coming soon.", "El emparejamiento automático llegará junto con el tablero en línea (fase 5).");
        Add(d, "Lobby.BetaHint", "Test server: your beta username and password. The password is sent once and never stored.", "Servidor de pruebas: usuario y contraseña de beta. La contraseña se envía una sola vez y no se guarda.");
        Add(d, "Lobby.Board", "Board", "Tablero");
        Add(d, "Lobby.CancelChallenge", "Cancel challenge", "Cancelar desafío");
        Add(d, "Lobby.Color", "Colour", "Color");
        Add(d, "Lobby.CreateChallenge", "Create challenge", "Crear desafío");
        Add(d, "Lobby.DoubleClickOpen", "Double-click to open on the board", "Doble clic para abrir en el tablero");
        Add(d, "Lobby.Google", "Continue with Google", "Continuar con Google");
        Add(d, "Lobby.GoogleBetaHint", "Google account? “Continue with Google” signs in to online-go.com. For beta you need a password (Settings → Account on beta.online-go.com) or a test account.", "¿Cuenta de Google? «Continuar con Google» entra en online-go.com. Para beta necesitas contraseña (Configuración → Cuenta en beta.online-go.com) o una cuenta de pruebas.");
        Add(d, "Lobby.GoogleTip", "Opens OGS in your browser (online-go.com); Hoshi never sees your Google account", "Se abre OGS en el navegador (online-go.com); Hoshi nunca ve tu cuenta de Google");
        Add(d, "Lobby.Handicap", "Handicap", "Hándicap");
        Add(d, "Lobby.MyGames", "My games", "Mis partidas");
        Add(d, "Lobby.NoChallenges", "No open challenges right now.", "No hay desafíos abiertos ahora mismo.");
        Add(d, "Lobby.NoGames", "You have no games in progress.", "No tienes partidas en curso.");
        Add(d, "Lobby.NoRanked", "Hoshi does not accept ranked games", "Hoshi no acepta partidas clasificatorias");
        Add(d, "Lobby.OAuthHint", "Your browser opens: sign in to OGS and authorise Hoshi. Hoshi never sees your credentials.", "Se abre tu navegador: entras en OGS y autorizas a Hoshi. Hoshi nunca ve tus credenciales.");
        Add(d, "Lobby.Open", "Open", "Abrir");
        Add(d, "Lobby.OpenChallenges", "Open challenges", "Desafíos abiertos");
        Add(d, "Lobby.Opponent", "Opponent", "Rival");
        Add(d, "Lobby.OpponentHint", "Empty = open challenge", "Vacío = desafío abierto");
        Add(d, "Lobby.Password", "Password", "Contraseña");
        Add(d, "Lobby.Refresh", "Refresh", "Actualizar");
        Add(d, "Lobby.Server", "Server", "Servidor");
        Add(d, "Lobby.SignIn", "Sign in", "Iniciar sesión");
        Add(d, "Lobby.SignInHeading", "Sign in to OGS", "Inicia sesión en OGS");
        Add(d, "Lobby.SignInOAuth", "Sign in with OGS", "Iniciar sesión con OGS");
        Add(d, "Lobby.SignOut", "Sign out", "Cerrar sesión");
        Add(d, "Lobby.Time", "Time", "Tiempo");
        Add(d, "Lobby.Title", "Play online", "Jugar en línea");
        Add(d, "Lobby.UnrankedNote", "Games created from Hoshi are always unranked. A direct challenge is private.", "Las partidas creadas desde Hoshi son siempre no clasificatorias. Un desafío directo es privado.");
        Add(d, "Lobby.Username", "Username", "Usuario");
        Add(d, "Main.AcceptScore", "Accept score", "Aceptar conteo");
        Add(d, "Main.AcceptUndo", "Accept undo", "Aceptar deshacer");
        Add(d, "Main.Analysis", "Analysis", "Análisis");
        Add(d, "Main.AnalysisTip", "Show the AI analysis: panel and suggestions on the board (A). KataGo always works in the background.", "Mostrar el análisis de la IA: panel y sugerencias en el tablero (A). KataGo trabaja siempre de fondo.");
        Add(d, "Main.BlackCaptures", "Stones captured by Black", "Piedras capturadas por negras");
        Add(d, "Main.BlackStone", "Black stone", "Piedra negra");
        Add(d, "Main.ChatHint", "Message your opponent (Enter)", "Escribe al rival (Enter)");
        Add(d, "Main.Circle", "Circle", "Círculo");
        Add(d, "Main.Comment", "Comment", "Comentario");
        Add(d, "Main.Cross", "Cross", "Cruz");
        Add(d, "Main.DeleteNode", "Delete node and variations", "Borrar nodo y variantes");
        Add(d, "Main.EditMode", "Edit mode", "Modo edición");
        Add(d, "Main.FinishEditing", "Finish editing", "Terminar edición");
        Add(d, "Main.First", "First (Home)", "Inicio (Home)");
        Add(d, "Main.GameInfo", "Game info…", "Información de la partida…");
        Add(d, "Main.GraphTip", "Black's estimated lead per move (up = Black). Click to go to that move.", "Ventaja estimada de negras por jugada (arriba = negras). Clic para ir a esa jugada.");
        Add(d, "Main.Label", "Label", "Etiqueta");
        Add(d, "Main.Last", "Last (End)", "Final (End)");
        Add(d, "Main.Leave", "Leave", "Salir");
        Add(d, "Main.LeaveTip", "Stop showing the game (it continues on OGS)", "Deja de mostrar la partida (sigue en OGS)");
        Add(d, "Main.MenuTip", "Menu: file, edit, online, preferences", "Menú: archivo, edición, en línea, preferencias");
        Add(d, "Main.New13", "New 13 × 13", "Nueva 13 × 13");
        Add(d, "Main.New19", "New 19 × 19", "Nueva 19 × 19");
        Add(d, "Main.New9", "New 9 × 9", "Nueva 9 × 9");
        Add(d, "Main.Next", "Next (→)", "Siguiente (→)");
        Add(d, "Main.Online", "Online", "En línea");
        Add(d, "Main.OnlineTip", "Play on OGS (Ctrl+L)", "Jugar en OGS (Ctrl+L)");
        Add(d, "Main.Open", "Open…", "Abrir…");
        Add(d, "Main.PassTip", "Pass (P)", "Pasar (P)");
        Add(d, "Main.PlayOnline", "Play online…", "Jugar en línea…");
        Add(d, "Main.Preferences", "Preferences…", "Preferencias…");
        Add(d, "Main.Previous", "Previous (←)", "Anterior (←)");
        Add(d, "Main.PromoteVariation", "Make main line", "Hacer línea principal");
        Add(d, "Main.RequestUndo", "Request undo", "Pedir deshacer");
        Add(d, "Main.Resign", "Resign", "Abandonar");
        Add(d, "Main.ResumeGame", "Resume game", "Reanudar partida");
        Add(d, "Main.Save", "Save", "Guardar");
        Add(d, "Main.SaveAs", "Save as…", "Guardar como…");
        Add(d, "Main.Square", "Square", "Cuadrado");
        Add(d, "Main.Territory", "Territory", "Territorio");
        Add(d, "Main.TerritoryTip", "Current and potential territory (T)", "Territorio actual y potencial (T)");
        Add(d, "Main.Triangle", "Triangle", "Triángulo");
        Add(d, "Main.Turn", "Turn", "Turno");
        Add(d, "Main.Undo", "Undo", "Deshacer");
        Add(d, "Main.UndoTip", "Undo (Ctrl+Z)", "Deshacer (Ctrl+Z)");
        Add(d, "Main.WhiteCaptures", "Stones captured by White", "Piedras capturadas por blancas");
        Add(d, "Main.WhiteStone", "White stone", "Piedra blanca");
        Add(d, "Prefs.AnimationsHint", "Animated background and stone animations. Turn them off if you prefer a still view.", "Fondo animado y animaciones al colocar piedras. Desactívalas si prefieres una vista quieta.");
        Add(d, "Prefs.Appearance", "Appearance", "Apariencia");
        Add(d, "Prefs.AtariBox", "Atari alert: the group trembles and sweats a little, with an “uh-oh” (not in live OGS games)", "Aviso de atari: el grupo tiembla y suda un poco, con un «uh-oh» (no en partidas de OGS en curso)");
        Add(d, "Prefs.Browse", "Browse…", "Examinar…");
        Add(d, "Prefs.Celebrate", "Celebrate strong moves", "Celebrar las jugadas fuertes");
        Add(d, "Prefs.CelebrateBox", "Sound and board impact when KataGo judges your move good, excellent or the best", "Sonido e impacto en el tablero cuando KataGo juzga tu jugada como buena, excelente o la mejor");
        Add(d, "Prefs.Config", "Configuration", "Configuración");
        Add(d, "Prefs.Done", "Done", "Listo");
        Add(d, "Prefs.Executable", "Executable", "Ejecutable");
        Add(d, "Prefs.KataGoIntro", "Hoshi uses KataGo (free, MIT) to judge every move and estimate territory. Download the package for your system from github.com/lightvector/KataGo/releases (OpenCL for most graphics cards, CUDA/TensorRT for NVIDIA, Eigen for CPU only) and a network from katagotraining.org. The package includes analysis_example.cfg.", "Hoshi usa KataGo (libre, MIT) para evaluar cada jugada y estimar el territorio. Descarga en github.com/lightvector/KataGo/releases el paquete de tu sistema (OpenCL para la mayoría de gráficas, CUDA/TensorRT para NVIDIA, Eigen para solo CPU) y una red desde katagotraining.org. El paquete trae analysis_example.cfg.");
        Add(d, "Prefs.LiveHint", "Analysis is live: KataGo shows partial results right away and keeps deepening the position up to the maximum visits. More visits = stronger, but more GPU use (with integrated graphics, 200–500 and a light network such as b18c384 or b10c128). During live OGS games analysis, territory and AI effects are off: OGS rules forbid AI help while you play.", "El análisis es en vivo: KataGo muestra resultados parciales enseguida y sigue profundizando en la posición hasta las visitas máximas. Más visitas = más fuerte, pero más uso de la GPU (con una gráfica integrada, 200–500 y una red ligera como b18c384 o b10c128). En partidas de OGS en curso el análisis y el territorio se desactivan: sus normas no permiten ayuda de IA mientras juegas.");
        Add(d, "Prefs.MaxVisits", "Maximum visits", "Visitas máximas");
        Add(d, "Prefs.Music", "Adaptive music", "Música adaptativa");
        Add(d, "Prefs.MusicBox", "Calm lo-fi that heats up with streaks of good moves and cools down with time or a mistake (key M)", "Lo-fi tranquilo que se anima con rachas de buenas jugadas y se calma con el tiempo o con un error (tecla M)");
        Add(d, "Prefs.Network", "Neural network", "Red neuronal");
        Add(d, "Prefs.StoneSoundsBox", "Soft sound for every stone placed and for captures (also when stepping through a game)", "Sonido suave al colocar cada piedra y al capturar (también al avanzar jugada a jugada)");
        Add(d, "Prefs.TestKataGo", "Test KataGo", "Probar KataGo");
        Add(d, "Prefs.TestSound", "Test sound", "Probar sonido");
        Add(d, "Prefs.BoardTab", "Board & stones", "Tablero y piedras");
        Add(d, "Prefs.BoardHint", "Mix any goban, stones and background with the theme you like. Choices apply at once.", "Combina cualquier goban, piedras y fondo con el tema que prefieras. Se aplica al momento.");
        Add(d, "Prefs.Board", "Goban", "Goban");
        Add(d, "Prefs.Stones", "Stones", "Piedras");
        Add(d, "Prefs.Background", "Background", "Fondo");
        Add(d, "Prefs.ResetSkins", "Use the theme's", "Usar los del tema");
        Add(d, "Prefs.ThemeHint", "The theme applies at once and is remembered.", "El tema se aplica al momento y se recuerda.");
        Add(d, "Prefs.Title", "Preferences", "Preferencias");
        Add(d, "Prefs.Volume", "Volume", "Volumen");
    }
}
