namespace Hoshi.Core.Localization;

public static partial class Tr
{
    static partial void AddViews(Dictionary<string, (string En, string Es)> d)
    {
        Add(d, "Prefs.Language", "Language", "Idioma");
        Add(d, "Main.Replays", "Played games…", "Partidas jugadas…");
        Add(d, "Replays.Title", "Played games", "Partidas jugadas");
        Add(d, "Replays.Hint", "Every game you play in Hoshi is kept here. Open one to review it: step forward with → and KataGo judges each move, with its effects and music.", "Aquí se guarda cada partida que juegas en Hoshi. Abre una para revisarla: avanza con → y KataGo valora cada jugada, con sus efectos y su música.");
        Add(d, "Replays.Review", "Review", "Revisar");
        Add(d, "Replays.Delete", "Delete", "Borrar");
        Add(d, "Replays.Empty", "No games yet. Games of 10 moves or more are kept automatically.", "Aún no hay partidas. Se guardan solas las de 10 jugadas o más.");
        Add(d, "Replays.Moves", "{0} moves", "{0} jugadas");
        Add(d, "Replays.NoResult", "no result", "sin resultado");
        Add(d, "Replays.Local", "local", "local");
        Add(d, "Replays.CouldNotOpen", "Could not open the game", "No se pudo abrir la partida");
        Add(d, "Prefs.Animations", "Animations", "Animaciones");
        Add(d, "Prefs.SoundsHelp",
            "Good: a dry knock · Excellent: an explosion with a shockwave and a shake · Best: a cinematic explosion, glowing cracks and a strong shake. The sounds are Hoshi's own; to use yours, put impact_small, explosion_medium, explosion_big or stone (.wav or .mp3) in {0}. The board impact needs animations on (Appearance).",
            "Buena: golpe seco · Excelente: explosión con onda expansiva y temblor · La mejor: explosión cinemática, grietas incandescentes y temblor fuerte. Los sonidos son de Hoshi; para usar los tuyos, pon impact_small, explosion_medium, explosion_big o stone (.wav o .mp3) en {0}. El impacto visual necesita las animaciones activadas (Apariencia).");
        Add(d, "Common.Cancel", "Cancel", "Cancelar");
        Add(d, "Common.Ok", "OK", "Aceptar");
        Add(d, "GameInfo.Date", "Date", "Fecha");
        Add(d, "GameInfo.DateFormat", "YYYY-MM-DD", "AAAA-MM-DD");
        Add(d, "GameInfo.Event", "Event", "Evento");
        Add(d, "GameInfo.Name", "Name", "Nombre");
        Add(d, "GameInfo.Place", "Place", "Lugar");
        Add(d, "GameInfo.Rank", "Rank", "Rango");
        Add(d, "GameInfo.Result", "Result", "Resultado");
        Add(d, "GameInfo.Rules", "Rules", "Reglas");
        Add(d, "GameInfo.Title", "Game info", "Información de la partida");
        Add(d, "Lobby.AutomatchSoon", "Automatic matchmaking is coming soon.", "El emparejamiento automático llegará junto con el tablero en línea (fase 5).");
        Add(d, "Lobby.BetaHint", "Test server: your beta username and password. The password is sent once and never stored.", "Servidor de pruebas: usuario y contraseña de beta. La contraseña se envía una sola vez y no se guarda.");
        Add(d, "Lobby.Board", "Board", "Tablero");
        Add(d, "Lobby.CancelChallenge", "Cancel challenge", "Cancelar desafío");
        Add(d, "Lobby.Color", "Colour", "Color");
        Add(d, "Lobby.CreateChallenge", "Create challenge", "Crear desafío");
        Add(d, "Lobby.DoubleClickOpen", "Double-click to open on the board", "Doble clic para abrir en el tablero");
        Add(d, "Lobby.Google", "Continue with Google", "Continuar con Google");
        Add(d, "Lobby.GoogleBetaHint", "Google account? “Continue with Google” signs in to online-go.com. For beta you need a password (Settings → Account on beta.online-go.com) or a test account.", "¿Cuenta de Google? «Continuar con Google» entra en online-go.com. Para beta necesitas contraseña (Configuración → Cuenta en beta.online-go.com) o una cuenta de pruebas.");
        Add(d, "Lobby.GoogleTip", "Opens OGS in your browser (online-go.com); Hoshi never sees your Google account", "Se abre OGS en el navegador (online-go.com); Hoshi nunca ve tu cuenta de Google");
        Add(d, "Lobby.Handicap", "Handicap", "Hándicap");
        Add(d, "Lobby.MyGames", "My games", "Mis partidas");
        Add(d, "Lobby.NoChallenges", "No open challenges right now.", "No hay desafíos abiertos ahora mismo.");
        Add(d, "Lobby.NoGames", "You have no games in progress.", "No tienes partidas en curso.");
        Add(d, "Lobby.NoRanked", "Hoshi does not accept ranked games", "Hoshi no acepta partidas clasificatorias");
        Add(d, "Lobby.OAuthHint", "Your browser opens: sign in to OGS and authorise Hoshi. Hoshi never sees your credentials.", "Se abre tu navegador: entras en OGS y autorizas a Hoshi. Hoshi nunca ve tus credenciales.");
        Add(d, "Lobby.Open", "Open", "Abrir");
        Add(d, "Lobby.OpenChallenges", "Open challenges", "Desafíos abiertos");
        Add(d, "Lobby.Opponent", "Opponent", "Rival");
        Add(d, "Lobby.OpponentHint", "Empty = open challenge", "Vacío = desafío abierto");
        Add(d, "Lobby.Password", "Password", "Contraseña");
        Add(d, "Lobby.Refresh", "Refresh", "Actualizar");
        Add(d, "Lobby.Server", "Server", "Servidor");
        Add(d, "Lobby.SignIn", "Sign in", "Iniciar sesión");
        Add(d, "Lobby.SignInHeading", "Sign in to OGS", "Inicia sesión en OGS");
        Add(d, "Lobby.SignInOAuth", "Sign in with OGS", "Iniciar sesión con OGS");
        Add(d, "Lobby.SignOut", "Sign out", "Cerrar sesión");
        Add(d, "Lobby.Time", "Time", "Tiempo");
        Add(d, "Lobby.Title", "Play online", "Jugar en línea");
        Add(d, "Lobby.UnrankedNote", "Games created from Hoshi are always unranked. A direct challenge is private.", "Las partidas creadas desde Hoshi son siempre no clasificatorias. Un desafío directo es privado.");
        Add(d, "Lobby.Username", "Username", "Usuario");
        Add(d, "Main.AcceptScore", "Accept score", "Aceptar conteo");
        Add(d, "Main.AcceptUndo", "Accept undo", "Aceptar deshacer");
        Add(d, "Main.Analysis", "Analysis", "Análisis");
        Add(d, "Main.AnalysisTip", "Show the AI analysis: panel and suggestions on the board (A). KataGo always works in the background.", "Mostrar el análisis de la IA: panel y sugerencias en el tablero (A). KataGo trabaja siempre de fondo.");
        Add(d, "Main.BlackCaptures", "Stones captured by Black", "Piedras capturadas por negras");
        Add(d, "Main.BlackStone", "Black stone", "Piedra negra");
        Add(d, "Main.ChatHint", "Message your opponent (Enter)", "Escribe al rival (Enter)");
        Add(d, "Main.Circle", "Circle", "Círculo");
        Add(d, "Main.Comment", "Comment", "Comentario");
        Add(d, "Main.Cross", "Cross", "Cruz");
        Add(d, "Main.DeleteNode", "Delete node and variations", "Borrar nodo y variantes");
        Add(d, "Main.EditMode", "Edit mode", "Modo edición");
        Add(d, "Main.FinishEditing", "Finish editing", "Terminar edición");
        Add(d, "Main.First", "First (Home)", "Inicio (Home)");
        Add(d, "Main.GameInfo", "Game info…", "Información de la partida…");
        Add(d, "Main.GraphTip", "Black's estimated lead per move (up = Black). Click to go to that move.", "Ventaja estimada de negras por jugada (arriba = negras). Clic para ir a esa jugada.");
        Add(d, "Main.Label", "Label", "Etiqueta");
        Add(d, "Main.Last", "Last (End)", "Final (End)");
        Add(d, "Main.Leave", "Leave", "Salir");
        Add(d, "Main.LeaveTip", "Stop showing the game (it continues on OGS)", "Deja de mostrar la partida (sigue en OGS)");
        Add(d, "Main.MenuTip", "Menu: file, edit, online, preferences", "Menú: archivo, edición, en línea, preferencias");
        Add(d, "Main.New13", "New 13 × 13", "Nueva 13 × 13");
        Add(d, "Main.New19", "New 19 × 19", "Nueva 19 × 19");
        Add(d, "Main.New9", "New 9 × 9", "Nueva 9 × 9");
        Add(d, "Main.Next", "Next (→)", "Siguiente (→)");
        Add(d, "Main.Online", "Online", "En línea");
        Add(d, "Main.OnlineTip", "Play on OGS (Ctrl+L)", "Jugar en OGS (Ctrl+L)");
        Add(d, "Main.Open", "Open…", "Abrir…");
        Add(d, "Main.PassTip", "Pass (P)", "Pasar (P)");
        Add(d, "Main.PlayOnline", "Play online…", "Jugar en línea…");
        Add(d, "Main.Preferences", "Preferences…", "Preferencias…");
        Add(d, "Main.Previous", "Previous (←)", "Anterior (←)");
        Add(d, "Main.PromoteVariation", "Make main line", "Hacer línea principal");
        Add(d, "Main.RequestUndo", "Request undo", "Pedir deshacer");
        Add(d, "Main.Resign", "Resign", "Abandonar");
        Add(d, "Main.ResumeGame", "Resume game", "Reanudar partida");
        Add(d, "Main.Save", "Save", "Guardar");
        Add(d, "Main.SaveAs", "Save as…", "Guardar como…");
        Add(d, "Main.Square", "Square", "Cuadrado");
        Add(d, "Main.Territory", "Territory", "Territorio");
        Add(d, "Main.TerritoryTip", "Current and potential territory (T)", "Territorio actual y potencial (T)");
        Add(d, "Main.Triangle", "Triangle", "Triángulo");
        Add(d, "Main.Turn", "Turn", "Turno");
        Add(d, "Main.Undo", "Undo", "Deshacer");
        Add(d, "Main.UndoTip", "Undo (Ctrl+Z)", "Deshacer (Ctrl+Z)");
        Add(d, "Main.WhiteCaptures", "Stones captured by White", "Piedras capturadas por blancas");
        Add(d, "Main.WhiteStone", "White stone", "Piedra blanca");
        Add(d, "Prefs.AnimationsHint", "Animated background and stone animations. Turn them off if you prefer a still view.", "Fondo animado y animaciones al colocar piedras. Desactívalas si prefieres una vista quieta.");
        Add(d, "Prefs.Appearance", "Appearance", "Apariencia");
        Add(d, "Prefs.AtariBox", "Atari alert: the group trembles and sweats a little, with an “uh-oh” (not in live OGS games)", "Aviso de atari: el grupo tiembla y suda un poco, con un «uh-oh» (no en partidas de OGS en curso)");
        Add(d, "Prefs.Browse", "Browse…", "Examinar…");
        Add(d, "Prefs.Celebrate", "Celebrate strong moves", "Celebrar las jugadas fuertes");
        Add(d, "Prefs.CelebrateBox", "Sound and board impact when KataGo judges your move good, excellent or the best", "Sonido e impacto en el tablero cuando KataGo juzga tu jugada como buena, excelente o la mejor");
        Add(d, "Prefs.Config", "Configuration", "Configuración");
        Add(d, "Prefs.Done", "Done", "Listo");
        Add(d, "Prefs.Executable", "Executable", "Ejecutable");
        Add(d, "Prefs.KataGoIntro", "Hoshi uses KataGo (free, MIT) to judge every move and estimate territory. Download the package for your system from github.com/lightvector/KataGo/releases (OpenCL for most graphics cards, CUDA/TensorRT for NVIDIA, Eigen for CPU only) and a network from katagotraining.org. The package includes analysis_example.cfg.", "Hoshi usa KataGo (libre, MIT) para evaluar cada jugada y estimar el territorio. Descarga en github.com/lightvector/KataGo/releases el paquete de tu sistema (OpenCL para la mayoría de gráficas, CUDA/TensorRT para NVIDIA, Eigen para solo CPU) y una red desde katagotraining.org. El paquete trae analysis_example.cfg.");
        Add(d, "Prefs.LiveHint", "Analysis is live: KataGo shows partial results right away and keeps deepening the position up to the maximum visits. More visits = stronger, but more GPU use (with integrated graphics, 200–500 and a light network such as b18c384 or b10c128). During live OGS games analysis, territory and AI effects are off: OGS rules forbid AI help while you play.", "El análisis es en vivo: KataGo muestra resultados parciales enseguida y sigue profundizando en la posición hasta las visitas máximas. Más visitas = más fuerte, pero más uso de la GPU (con una gráfica integrada, 200–500 y una red ligera como b18c384 o b10c128). En partidas de OGS en curso el análisis y el territorio se desactivan: sus normas no permiten ayuda de IA mientras juegas.");
        Add(d, "Prefs.MaxVisits", "Maximum visits", "Visitas máximas");
        Add(d, "Prefs.Music", "Adaptive music", "Música adaptativa");
        Add(d, "Prefs.MusicBox", "Calm lo-fi that heats up with streaks of good moves and cools down with time or a mistake (key M)", "Lo-fi tranquilo que se anima con rachas de buenas jugadas y se calma con el tiempo o con un error (tecla M)");
        Add(d, "Prefs.Network", "Neural network", "Red neuronal");
        Add(d, "Prefs.StoneSoundsBox", "Soft sound for every stone placed and for captures (also when stepping through a game)", "Sonido suave al colocar cada piedra y al capturar (también al avanzar jugada a jugada)");
        Add(d, "Prefs.TestKataGo", "Test KataGo", "Probar KataGo");
        Add(d, "Prefs.TestSound", "Test sound", "Probar sonido");
        Add(d, "Prefs.ThemeHint", "The theme applies at once and is remembered.", "El tema se aplica al momento y se recuerda.");
        Add(d, "Prefs.Title", "Preferences", "Preferencias");
        Add(d, "Prefs.Volume", "Volume", "Volumen");
    }
}
