#!/usr/bin/env python3
"""Generates src/Hoshi.App/Themes/IconSets.g.cs from the SVGs of Phosphor (MIT), Lucide (ISC) and Tabler (MIT).

Usage: python3 tools/gen_icons.py <phosphor-core/package> <lucide-static/package> <tabler-icons/package>
Every SVG element (path, circle, line, polyline, polygon, rect, ellipse) becomes SVG path data that
Avalonia's Geometry.Parse understands. Re-run when icons are added; the output is committed.
"""
import re, sys, xml.etree.ElementTree as ET
from pathlib import Path

ICONS = {  # key: (phosphor, lucide, tabler)
    "First": ("skip-back", "skip-back", "player-skip-back"),
    "Previous": ("caret-left", "chevron-left", "chevron-left"),
    "Next": ("caret-right", "chevron-right", "chevron-right"),
    "Last": ("skip-forward", "skip-forward", "player-skip-forward"),
    "Pass": ("hand-palm", "hand", "hand-stop"),
    "Undo": ("arrow-counter-clockwise", "undo-2", "arrow-back-up"),
    "Online": ("globe-hemisphere-west", "globe", "world"),
    "Menu": ("list", "menu", "menu-2"),
    "Edit": ("pencil-simple", "pencil", "pencil"),
    "Settings": ("gear-six", "settings", "settings"),
    "Resign": ("flag", "flag", "flag"),
    "Triangle": ("triangle", "triangle", "triangle"),
    "Square": ("square", "square", "square"),
    "Circle": ("circle", "circle", "circle"),
    "Cross": ("x", "x", "x"),
    "Label": ("text-aa", "type", "typography"),
    "Chat": ("chat-circle", "message-circle", "message-circle"),
    "SignOut": ("sign-out", "log-out", "logout"),
    "Star": ("star-four", "sparkle", "sparkles"),
    "Check": ("check", "check", "check"),
    "Close": ("x", "x", "x"),
    "Territory": ("squares-four", "grid-2x2", "layout-grid"),
    "Analysis": ("brain", "brain", "brain"),
    "Folder": ("folder-open", "folder-open", "folder-open"),
    "Volume": ("speaker-high", "volume-2", "volume"),
    "Muted": ("speaker-slash", "volume-x", "volume-off"),
    "Engine": ("robot", "bot", "robot"),
}

def num(v): return float(v)

def fmt(x): return ("%.3f" % x).rstrip("0").rstrip(".")

def element_to_path(el):
    tag = el.tag.split("}")[-1]
    a = el.attrib
    if a.get("stroke") == "none" and a.get("fill") == "none":
        return None  # Tabler's invisible bounding box
    if tag == "path":
        return a["d"]
    if tag == "circle":
        cx, cy, r = num(a["cx"]), num(a["cy"]), num(a["r"])
        return f"M{fmt(cx - r)},{fmt(cy)} a{fmt(r)},{fmt(r)} 0 1,0 {fmt(2*r)},0 a{fmt(r)},{fmt(r)} 0 1,0 {fmt(-2*r)},0 Z"
    if tag == "ellipse":
        cx, cy, rx, ry = num(a["cx"]), num(a["cy"]), num(a["rx"]), num(a["ry"])
        return f"M{fmt(cx - rx)},{fmt(cy)} a{fmt(rx)},{fmt(ry)} 0 1,0 {fmt(2*rx)},0 a{fmt(rx)},{fmt(ry)} 0 1,0 {fmt(-2*rx)},0 Z"
    if tag == "line":
        return f"M{a['x1']},{a['y1']} L{a['x2']},{a['y2']}"
    if tag in ("polyline", "polygon"):
        pts = re.split(r"[\s,]+", a["points"].strip())
        pairs = [f"{pts[i]},{pts[i+1]}" for i in range(0, len(pts) - 1, 2)]
        return "M" + " L".join(pairs) + (" Z" if tag == "polygon" else "")
    if tag == "rect":
        x, y = num(a.get("x", 0)), num(a.get("y", 0))
        w, h = num(a["width"]), num(a["height"])
        rx = num(a.get("rx", a.get("ry", 0)))
        ry = num(a.get("ry", rx))
        if rx == 0:
            return f"M{fmt(x)},{fmt(y)} h{fmt(w)} v{fmt(h)} h{fmt(-w)} Z"
        return (f"M{fmt(x+rx)},{fmt(y)} h{fmt(w-2*rx)} a{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(rx)},{fmt(ry)} v{fmt(h-2*ry)} "
                f"a{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(-rx)},{fmt(ry)} h{fmt(-(w-2*rx))} a{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(-rx)},{fmt(-ry)} "
                f"v{fmt(-(h-2*ry))} a{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(rx)},{fmt(-ry)} Z")
    return None

def load(svg_path):
    root = ET.parse(svg_path).getroot()
    vb = [float(v) for v in root.attrib["viewBox"].split()]
    parts = [p for el in root.iter() if el is not root for p in [element_to_path(el)] if p]
    return vb[2], " ".join(parts)

def main():
    phosphor, lucide, tabler = map(Path, sys.argv[1:4])
    sets = {
        "PhosphorLight": (lambda n: phosphor / "assets/light" / f"{n}-light.svg", 0, False, 0),
        "PhosphorRegular": (lambda n: phosphor / "assets/regular" / f"{n}.svg", 0, False, 0),
        "Lucide": (lambda n: lucide / "icons" / f"{n}.svg", 1, True, 2),
        "Tabler": (lambda n: tabler / "icons/outline" / f"{n}.svg", 2, True, 2),
    }
    out = ["// <auto-generated> by tools/gen_icons.py. Do not edit by hand.",
           "// Phosphor Icons (MIT, © Phosphor Icons), Lucide (ISC, © Lucide Contributors), Tabler Icons (MIT, © Paweł Kuna).",
           "// See THIRD_PARTY_NOTICES.md.", "", "namespace Hoshi.App.Themes;", "",
           "internal static class IconSets", "{",
           "    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, IconData>> All =",
           "        new Dictionary<string, IReadOnlyDictionary<string, IconData>>", "        {"]
    for set_name, (path_of, idx, stroke, width) in sets.items():
        out.append(f'            ["{set_name}"] = new Dictionary<string, IconData>')
        out.append("            {")
        for key, names in ICONS.items():
            size, data = load(path_of(names[idx]))
            data = data.replace('"', '\\"')
            out.append(f'                ["{key}"] = new("{data}", {fmt(size)}, {"true" if stroke else "false"}, {width}),')
        out.append("            },")
    out += ["        };", "}", ""]
    Path("src/Hoshi.App/Themes/IconSets.g.cs").write_text("\n".join(out))
    print("icons:", len(ICONS), "x", len(sets))

main()
